from __future__ import annotations

"""Column expectations derived from docs/prd/affiliate-system/20_data/awin_feed_mapping.md."""

REQUIRED_COLUMNS = [
    "aw_product_id",
    "merchant_product_id",
    "product_name",
    "aw_deep_link",
    "merchant_image_url",
    "description",
    "merchant_category",
    "search_price",
    "merchant_name",
    "merchant_id",
    "category_name",
    "category_id",
    "currency",
    "display_price",
    "data_feed_id",
]

ROBUST_MATCHING_COLUMNS = [
    "brand_name",
    "brand_id",
    "ean",
    "upc",
    "mpn",
    "product_GTIN",
    "parent_product_id",
    "merchant_product_category_path",
    "merchant_product_second_category",
    "merchant_product_third_category",
    "product_type",
    "keywords",
    "specifications",
    "in_stock",
    "stock_quantity",
    "stock_status",
    "is_for_sale",
    "web_offer",
    "pre_order",
    "valid_from",
    "valid_to",
    "delivery_cost",
    "delivery_time",
    "large_image",
    "merchant_thumb_url",
    "alternate_image",
    "alternate_image_two",
    "alternate_image_three",
    "alternate_image_four",
    "commission_group",
]

RECOMMENDED_COLUMNS = [
    "aw_deep_link",
    "product_name",
    "aw_product_id",
    "merchant_product_id",
    "merchant_image_url",
    "description",
    "merchant_category",
    "search_price",
    "merchant_name",
    "merchant_id",
    "category_name",
    "category_id",
    "aw_image_url",
    "currency",
    "store_price",
    "delivery_cost",
    "merchant_deep_link",
    "language",
    "last_updated",
    "display_price",
    "data_feed_id",
    "brand_name",
    "brand_id",
    "colour",
    "product_short_description",
    "specifications",
    "condition",
    "product_model",
    "model_number",
    "dimensions",
    "keywords",
    "product_type",
    "commission_group",
    "merchant_product_category_path",
    "merchant_product_second_category",
    "merchant_product_third_category",
    "rrp_price",
    "saving",
    "savings_percent",
    "base_price",
    "base_price_amount",
    "base_price_text",
    "product_price_old",
    "delivery_restrictions",
    "delivery_weight",
    "warranty",
    "terms_of_contract",
    "delivery_time",
    "in_stock",
    "stock_quantity",
    "valid_from",
    "valid_to",
    "is_for_sale",
    "web_offer",
    "pre_order",
    "stock_status",
    "size_stock_status",
    "size_stock_amount",
    "merchant_thumb_url",
    "large_image",
    "alternate_image",
    "aw_thumb_url",
    "alternate_image_two",
    "alternate_image_three",
    "alternate_image_four",
    "reviews",
    "average_rating",
    "rating",
    "number_available",
    "custom_1",
    "custom_2",
    "custom_3",
    "custom_4",
    "custom_5",
    "custom_6",
    "custom_7",
    "custom_8",
    "custom_9",
    "ean",
    "isbn",
    "upc",
    "mpn",
    "parent_product_id",
    "product_GTIN",
    "basket_link",
]


def compare_columns(header: list[str]) -> dict[str, list[str]]:
    header_set = {column.strip() for column in header if column.strip()}
    return {
        "required_columns_present": [
            column for column in REQUIRED_COLUMNS if column in header_set
        ],
        "required_columns_missing": [
            column for column in REQUIRED_COLUMNS if column not in header_set
        ],
        "robust_matching_columns_present": [
            column for column in ROBUST_MATCHING_COLUMNS if column in header_set
        ],
        "robust_matching_columns_missing": [
            column for column in ROBUST_MATCHING_COLUMNS if column not in header_set
        ],
        "recommended_columns_present": [
            column for column in RECOMMENDED_COLUMNS if column in header_set
        ],
        "recommended_columns_missing": [
            column for column in RECOMMENDED_COLUMNS if column not in header_set
        ],
    }
